# Generated by Django 4.1 on 2022-08-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labs',
            new_name='Lab',
        ),
    ]
